### ISSUE TITLE
Imprint

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docs-as-co.de#11]
Do we need the Google-Analytics imprint? Or do we just drop Google Analytics?

https://github.com/docToolchain/docs-as-co.de/blob/master/docs/_pages/imprint-privacy.md

**Comment by gernotstarke** [comment]
we DEFINITELY drop Analytics - the organizational overhead to get this GDPR-compliant is imho too large. It has imho NO benefit for us!

**Comment by rdmueller** [comment]
ok. so I've just removed the google analytics imprint.
But we still have two 3rd party cookies which we should analyze...

**Comment by gernotstarke** [comment]
what other cookies??

**Comment by rdmueller** [comment]
seems to be font awesome (I think we can kick this) and something other.
In addition, the youtube videos use cookies. 
I could render the videos as gifs but then those mb will be histed by netlify...

**Comment by gernotstarke** [comment]
suggestions:
* add the required fontawesome copyright etc stuff to the imprint
* add the quotube stuff to the imprint
* add a little javascript snippet (cookie consent) - I can copy that from arc42.org

**Comment by gernotstarke** [comment]
* fontawesome: done

* cookie consent: done, but should eventually be moved to BOTTOM of page instead of TOP
