### ISSUE TITLE
page excerpt on "getting started" is not readable

### ISSUE THREAD

**Issue by gernotstarke** [docToolchain/docs-as-co.de#13]
white on light-gray image is not readable...

Either use a dark image, or a more compact "slug" (my suggestion).

As the existing "summary" is nice, we could move it to a "quotation" on the page itself"

**Comment by rdmueller** [comment]
the minimal mistakes template also supports filters (already applied on the docs-page. This would be an easy way to make the image darker...

**Comment by gernotstarke** [comment]
I forgot about that feature... Let's try...


Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.
