### ISSUE TITLE
create favicon

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docs-as-co.de#3]

**Comment by gernotstarke** [comment]
I suggest you use https://realfavicongenerator.net/ (that's what we used for the arc42.org sites)

(or you point me to any svg/vector image of the logo you want to use...)

**Comment by gernotstarke** [comment]
created a pr...
![android-chrome-192x192](https://user-images.githubusercontent.com/1233990/46486400-5d91df00-c806-11e8-8dea-87f4e21e806f.png)

**Comment by rdmueller** [comment]
that looks funny 😁

**Comment by rdmueller** [comment]
fixed. thanx!
