### ISSUE TITLE
Preview images are missing in Firefox and IE

### ISSUE THREAD

**Issue by feststelltaste** [docToolchain/docs-as-co.de#51]
The "You May Also Enjoy" section refers to recommended articles. It seems that the preview images are missing (in Firefox Quantum 66.0.5 (64-Bit) and Internet Explorer 11 on Windows 10, not in Chrome or Edge):

Firefox: 

![grafik](https://user-images.githubusercontent.com/1470822/57694138-3bd5c180-764b-11e9-98e8-942db6a42192.png)

Internet Explorer:

<img width="788" alt="2019-05-14 13_28_02-Docs-as-Code at JAX conference - Docs-as-Code - Internet Explorer" src="https://user-images.githubusercontent.com/1470822/57694531-3fb61380-764c-11e9-8af3-34be358ecda8.png">

You can find an example on https://docs-as-co.de/news/jax2019/ at the bottom.

**Comment by rdmueller** [comment]
thanx. That is funny. I even didn't know that there should be previews...
ok. these are not previews, they are splash images. I have to check how they should be selected...

**Comment by rdmueller** [comment]
should be fixed. Thanx for the report, I will close this now.
