### ISSUE TITLE
provide docker container so we can test the build locally without interfering with existing jekyll/ruby installations

### ISSUE THREAD

**Issue by gernotstarke** [docToolchain/docs-as-co.de#8]
I host approx 6 websites with different jekyll versions... and don't want to modify my local setup
by calling "bundle install"... as that would surely cause some (negative) side effects...

Maybe "testcontainers" would also be a good idea...

**Comment by rdmueller** [comment]
hm. I've re-used your code - doesn't it come with the docker files to build the container?
I had some problems to make it work, but I will keep on trying (you know about my problems with docker, don't you? ;-)

btw: I was very surprised to see that netlify comes with a preview-deployment for PRs - have you already spotted it? The link to the preview is directly accessible from the PR...

**Comment by gernotstarke** [comment]
done and good enough. I close this issue.
