### ISSUE TITLE
add content to "get-started" 

### ISSUE THREAD

**Issue by gernotstarke** [docToolchain/docs-as-co.de#9]
[] quickstart: use gradle (siehe Kolumne Folge 1)
[] I cannot use gradle: use Docker (to be done)
[] I like it, I want the full package: use docToolchain
[] Additional options: PlantUML, EnterpriseArchitect(tm), Confluence(tm), ... (to be done)

**Comment by rdmueller** [comment]
added online editor, asciidoctorj, gradle and now maven example

[ ] check maven example and create short video
[ ] fix IDE overview

**Comment by gernotstarke** [comment]
I suggest to move the "Quickstart" stuff directly to "getting started" (I'll do that...)

**Comment by gernotstarke** [comment]
did netlify build this commit? I don't see my changes reflected on the site...

**Comment by gernotstarke** [comment]
at least my "push" worked..

**Comment by rdmueller** [comment]
netlify failed. I just triggered a rebuild...

**Comment by rdmueller** [comment]
should build now. I've also updated the asciidoctorj video (bigger font, watermark) and added the maven video....
